--INSERT INTO kur_kurser (kur_nb_refkurs, kur_sist_endr_dato) VALUES (1.0000, '2013-10-28 00:00:00');
INSERT INTO PHONE (ID, NAME, SNIPPET, IMAGEURL, AGE) VALUES ('motorola-xoom-with-wi-fi',  'Motorola XOOM\u2122 with Wi-Fi', 'The Next, Next Generation\r\n\r\nExperience the future with Motorola XOOM with Wi-Fi, the world´s first tablet powered by Android 3.0 (Honeycomb).', 'img/phones/motorola-xoom-with-wi-fi.0.jpg', 0);
INSERT INTO PHONE (ID, NAME, SNIPPET, IMAGEURL, AGE) VALUES ('motorola-xoom', 'MOTOROLA XOOM\u2122', 'The Next, Next Generation\n\nExperience the future with MOTOROLA XOOM, the world´s first tablet powered by Android 3.0 (Honeycomb).', 'img/phones/motorola-xoom.0.jpg', 1);
INSERT INTO PHONE (ID, NAME, SNIPPET, IMAGEURL, AGE) VALUES ('motorola-atrix-4g', 'MOTOROLA ATRIX\u2122 4G', 'MOTOROLA ATRIX 4G the world´s most powerful smartphone.', 'img/phones/motorola-atrix-4g.0.jpg', 2);
INSERT INTO PHONE (ID, NAME, SNIPPET, IMAGEURL, AGE) VALUES ('dell-streak-7', 'Dell Streak 7', 'Introducing Dell\u2122 Streak 7. Share photos, videos and movies together. It\u2019s small enough to carry around, big enough to gather around.', 'img/phones/dell-streak-7.0.jpg', 3); 
INSERT INTO PHONE (ID, NAME, SNIPPET, IMAGEURL, AGE) VALUES ('samsung-gem', 'Samsung Gem\u2122', 'The Samsung Gem\u2122 brings you everything that you would expect and more from a touch display smart phone \u2013 more apps, more features and a more affordable price.', 'img/phones/samsung-gem.0.jpg', 4);

INSERT INTO PHONE_DETAILS (ID, NAME, DESCRIPTION, IMAGEURLS, ADDITIONAL_FEATURES, AVAILABILITY, GPS, INFRARED) VALUES ('motorola-xoom-with-wi-fi', 'Motorola XOOM\u2122 with Wi-Fi', 'Motorola XOOM with Wi-Fi has a super-powerful dual-core processor and Android\u2122 3.0 (Honeycomb) \u2014 the Android platform designed specifically for tablets. With its 10.1-inch HD widescreen display, you\u2019ll enjoy HD video in a thin, light, powerful and upgradeable tablet.', 'img/phones/motorola-xoom-with-wi-fi.0.jpg,img/phones/motorola-xoom-with-wi-fi.1.jpg,img/phones/motorola-xoom-with-wi-fi.2.jpg,img/phones/motorola-xoom-with-wi-fi.3.jpg,img/phones/motorola-xoom-with-wi-fi.4.jpg,img/phones/motorola-xoom-with-wi-fi.5.jpg', 'Sensors: proximity, ambient light, barometer, gyroscope', '', 1, 0);
INSERT INTO PHONE_DETAILS (ID, NAME, DESCRIPTION, IMAGEURLS, ADDITIONAL_FEATURES, AVAILABILITY, GPS, INFRARED) VALUES ('motorola-xoom', 'MOTOROLA XOOM\u2122', 'MOTOROLA XOOM has a super-powerful dual-core processor and Android\u2122 3.0 (Honeycomb) \u2014 the Android platform designed specifically for tablets. With its 10.1-inch HD widescreen display, you\u2019ll enjoy HD video in a thin, light, powerful and upgradeable tablet.', 'img/phones/motorola-xoom.0.jpg,img/phones/motorola-xoom.1.jpg,img/phones/motorola-xoom.2.jpg', 'Front-facing camera. Sensors: proximity, ambient light, barometer, gyroscope.', 'Verizon', 0, 1);
INSERT INTO PHONE_DETAILS (ID, NAME, DESCRIPTION, IMAGEURLS, ADDITIONAL_FEATURES, AVAILABILITY, GPS, INFRARED) VALUES ('motorola-atrix-4g', 'MOTOROLA ATRIX\u2122 4G', 'MOTOROLA ATRIX 4G gives you dual-core processing power and the revolutionary webtop application. With webtop and a compatible Motorola docking station, sold separately, you can surf the Internet with a full Firefox browser, create and edit docs, or access multimedia on a large screen almost anywhere.', 'img/phones/motorola-atrix-4g.0.jpg,img/phones/motorola-atrix-4g.1.jpg,img/phones/motorola-atrix-4g.2.jpg,img/phones/motorola-atrix-4g.3.jpg', '', 'AT&T', 1, 0);
INSERT INTO PHONE_DETAILS (ID, NAME, DESCRIPTION, IMAGEURLS, ADDITIONAL_FEATURES, AVAILABILITY, GPS, INFRARED) VALUES ('dell-streak-7', 'Dell Streak 7', 'Introducing Dell\u2122 Streak 7. Share photos, videos and movies together. It\u2019s small enough to carry around, big enough to gather around. Android\u2122 2.2-based tablet with over-the-air upgrade capability for future OS releases.  A vibrant 7-inch, multitouch display with full Adobe\u00ae Flash 10.1 pre-installed.  Includes a 1.3 MP front-facing camera for face-to-face chats on popular services such as Qik or Skype.  16 GB of internal storage, plus Wi-Fi, Bluetooth and built-in GPS keeps you in touch with the world around you.  Connect on your terms. Save with 2-year contract or flexibility with prepaid pay-as-you-go plans', 'img/phones/dell-streak-7.0.jpg,img/phones/dell-streak-7.1.jpg,img/phones/dell-streak-7.2.jpg,img/phones/dell-streak-7.3.jpg,img/phones/dell-streak-7.4.jpg', 'Front Facing 1.3MP Camera', 'T-Mobile', 1, 0);
INSERT INTO PHONE_DETAILS (ID, NAME, DESCRIPTION, IMAGEURLS, ADDITIONAL_FEATURES, AVAILABILITY, GPS, INFRARED) VALUES ('samsung-gem', 'Samsung Gem\u2122', 'The Samsung Gem\u2122 maps a route to a smarter mobile experience. By pairing one of the fastest processors in the category with the Android\u2122 platform, the Gem delivers maximum multitasking speed and social networking capabilities to let you explore new territory online. A smart phone at an even smarter price is a real find, so uncover the Gem and discover what\u2019s next.', 'img/phones/samsung-gem.0.jpg,img/phones/samsung-gem.1.jpg,img/phones/samsung-gem.2.jpg', '3.2\u201d Full touch screen with Advanced anti smudge, anti reflective and anti scratch glass; Swype text input for easy and fast message creation; multiple messaging options, including text with threaded messaging for organized, easy-to-follow text; Social Community support, including Facebook and MySpace; Next generation Address book; Visual Voice Mail\n', 'Cellular South', 1, 0);
